# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.0518614 0.76572 8 1 2 -2.01488e-07 0.999999 

0.981939 0.633479 7 1 2 -2.39341e-07 0.999999 

0.990671 0.67072 6 1 2 -8.00836e-08 0.999999 

0.97115 0.737107 5 1 2 4.09829e-08 0.999999 

0.533167 0.787226 9 0.999999 2 -1.23029e-08 1 

