# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <T> <function> 
0.499333 0.0103123 0 1 0.99998 

0.513861 0.0124161 1 1 0.999981 

0.906349 0.218649 2 0.00492534 0.0276996 

0.569612 0.312231 4 2.66273e-06 9.92411e-05 

0.646934 0.293284 3 8.10222e-06 -0.000120759 

