# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <T> <function> 
0.503524 0.0103346 0 1 1 

0.518798 0.0124484 1 1 1 

0.906719 0.233091 2 0.00492534 -0.0234841 

0.650597 0.304893 3 8.10222e-06 -0.000140941 

0.572167 0.320658 4 2.66273e-06 3.98719e-06 

