# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <T> <function> 
0.465603 0.736665 5 0 2.04513e-12 

0.603769 0.666159 6 0 -8.23092e-13 

0.662439 0.626557 7 0 1.26956e-10 

0.486466 0.764985 8 0 6.64598e-13 

0.877698 0.782952 9 0 2.67216e-13 

