FROM dealii/dealii:v8.5.0-gcc-mpi-fulldepscandi-debugrelease

MAINTAINER rene.gassmoeller@mailbox.org

#User and group of the 'jenkins' user
USER root
#USER 10000:10000

ENV OMPI_MCA_btl_base_warn_component_unused=0
