name: github-docker

on: 
  push: 
    branches:
      - 'aspect-*'
      - 'main'
      - 'daily_container_build'

concurrency:
  group: docker-build
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN }}

      - name: Build and push Docker image of master 
        uses: docker/build-push-action@v3
        with:
          context: ./contrib/docker/docker/
          cache-to: type=inline
          push: false # ${{github.ref_name == 'master'}}
          tags: gassmoeller/aspect:main

