name: github-docker

on: 
  push: 
    branches:
      - 'main'
      - 'daily_container_build'
  release:

concurrency:
  group: docker-build
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN }}

      - name: Build and push Docker image for main
        uses: docker/build-push-action@v3
        if: ${{ github.event_name }} == "push"
        with:
          context: ./contrib/docker/docker/
          cache-from: type=registry,ref=dealii/dealii:v9.4.0-focal
          cache-to: type=inline
          push: true
          tags: gassmoeller/aspect:latest

      - name: Build and push Docker image for release
        uses: docker/build-push-action@v3
        if: ${{ github.event_name }} == "release"
        with:
          context: ./contrib/docker/docker/
          cache-from: type=registry,ref=dealii/dealii:v9.4.0-focal
          cache-to: type=inline
          push: true
          tags: gassmoeller/aspect:${{github.ref_name}}

